version: '3.9'

services:
  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- --port 3000 --hostname 0.0.0.0"
    environment:
      - BACKEND_URL=http://backend:8000
    ports:
      - "3100:3000"

  backend:
    build: ./backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8100:8000"
