version: '3.9'

services:
  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- --port 3000 --hostname 0.0.0.0"
    ports:
      - "${FRONTEND_PORT:-3000}:3000"

  backend:
    build: ./backend
    working_dir: /app
    volumes:
      - ./backend:/app
      - /var/run/docker.sock:/var/run/docker.sock
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "${BACKEND_PORT:-8000}:8000"
