version: '3.9'
services:
  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev"
    environment:
      - BACKEND_URL=http://backend:8000
      - PORT=${FRONTEND_PORT:-3000}
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    depends_on:
      - backend
  backend:
    build: ./backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "${BACKEND_PORT:-8000}:8000"
